CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE TABLE "Photos" (
        "Id" text NOT NULL,
        "Url" text NULL,
        CONSTRAINT "PK_Photos" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE TABLE "Clothes" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Description" text NULL,
        "Status" integer NOT NULL,
        "PhotoId" text NULL,
        CONSTRAINT "PK_Clothes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clothes_Photos_PhotoId" FOREIGN KEY ("PhotoId") REFERENCES "Photos" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE TABLE "Offerings" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ClothId" integer NOT NULL,
        "ReferenceLink" text NULL,
        "Price" numeric NOT NULL,
        "TradeType" integer NOT NULL,
        "DeliveryType" integer NOT NULL,
        "OfferingDate" timestamp without time zone NOT NULL,
        "OrderedDate" timestamp without time zone NULL,
        "SendDate" timestamp without time zone NULL,
        CONSTRAINT "PK_Offerings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Offerings_Clothes_ClothId" FOREIGN KEY ("ClothId") REFERENCES "Clothes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE TABLE "Purchases" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ClothId" integer NOT NULL,
        "ReferenceLink" text NULL,
        "Price" numeric NOT NULL,
        "TradeType" integer NOT NULL,
        "DeliveryType" integer NOT NULL,
        "PurchaseDate" timestamp without time zone NOT NULL,
        "PaymentDate" timestamp without time zone NULL,
        "DeliveryDate" timestamp without time zone NULL,
        CONSTRAINT "PK_Purchases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Purchases_Clothes_ClothId" FOREIGN KEY ("ClothId") REFERENCES "Clothes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE INDEX "IX_Clothes_PhotoId" ON "Clothes" ("PhotoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE INDEX "IX_Offerings_ClothId" ON "Offerings" ("ClothId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    CREATE INDEX "IX_Purchases_ClothId" ON "Purchases" ("ClothId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829084431_PostgresInit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210829084431_PostgresInit', '3.1.4');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210922111041_ClothStorage') THEN
    ALTER TABLE "Clothes" ADD "DetailedStorageInfo" text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210922111041_ClothStorage') THEN
    ALTER TABLE "Clothes" ADD "StorageInfo" text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210922111041_ClothStorage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210922111041_ClothStorage', '3.1.4');
    END IF;
END $$;
